//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.AssociatedRisk> MyAssignedRisks()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.AssociatedRisk> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.AssociatedRisk>("AssociatedRisks");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ChangeQualificationAction> MyChangeQualificationActions()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ChangeQualificationAction> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.ChangeQualificationAction>("ChangeQualificationActions");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ChangeQualification> MyChangeQualifications()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ChangeQualification> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.ChangeQualification>("ChangeQualifications");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ChangeRequest> MyChangeRequests()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ChangeRequest> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.ChangeRequest>("ChangeRequests");
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.AssociatedRisk))
            {
                return new global::LightSwitchApplication.Implementation.AssociatedRisk();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ChangeQualificationAction))
            {
                return new global::LightSwitchApplication.Implementation.ChangeQualificationAction();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ChangeQualification))
            {
                return new global::LightSwitchApplication.Implementation.ChangeQualification();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ChangeRequest))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequest();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ChangeRequestStatus))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequestStatus();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.AssociatedRisk))
            {
                return new global::LightSwitchApplication.Implementation.AssociatedRisk();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeQualificationAction))
            {
                return new global::LightSwitchApplication.Implementation.ChangeQualificationAction();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeQualification))
            {
                return new global::LightSwitchApplication.Implementation.ChangeQualification();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeRequest))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequest();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeRequestStatus))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequestStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.AssociatedRisk) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssociatedRisk);
            }
            if (typeof(global::LightSwitchApplication.ChangeQualificationAction) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeQualificationAction);
            }
            if (typeof(global::LightSwitchApplication.ChangeQualification) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeQualification);
            }
            if (typeof(global::LightSwitchApplication.ChangeRequest) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeRequest);
            }
            if (typeof(global::LightSwitchApplication.ChangeRequestStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeRequestStatus);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssociatedRisk :
        global::LightSwitchApplication.AssociatedRisk.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssociatedRisk.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssociatedRisk.DetailsClass.IImplementation.ChangeRequest
        {
            get
            {
                return this.ChangeRequest;
            }
            set
            {
                this.ChangeRequest = (global::LightSwitchApplication.Implementation.ChangeRequest)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ChangeRequest");
                }
            }
        }
        
        partial void OnRiskAssessment_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("AssignedTo");
            }
        }
        
        partial void OnChangeRequest_AssociatedRiskChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ChangeRequest");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeQualificationAction :
        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.IImplementation.ChangeQualification
        {
            get
            {
                return this.ChangeQualification;
            }
            set
            {
                this.ChangeQualification = (global::LightSwitchApplication.Implementation.ChangeQualification)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ChangeQualification");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.IImplementation.ActionAssignedTo
        {
            get
            {
                return this.ActionAssignedTo;
            }
            set
            {
                this.ActionAssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActionAssignedTo");
                }
            }
        }
        
        partial void OnChangeQualificationAction_ChangeQualificationChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ChangeQualification");
            }
        }
        
        partial void OnChangeQualificationAction_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActionAssignedTo");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeQualification :
        global::LightSwitchApplication.ChangeQualification.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeQualification.DetailsClass.IImplementation.ChangeRequest
        {
            get
            {
                return this.ChangeRequest;
            }
            set
            {
                this.ChangeRequest = (global::LightSwitchApplication.Implementation.ChangeRequest)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ChangeRequest");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeQualification.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeQualification.DetailsClass.IImplementation.ChangeQualificationActions
        {
            get
            {
                return this.ChangeQualificationActions;
            }
        }
        
        partial void OnChangeQualification_ChangeRequestChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ChangeRequest");
            }
        }
        
        partial void OnChangeQualification_Employee1Changed()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("AssignedTo");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeRequest :
        global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.RaisedBy
        {
            get
            {
                return this.RaisedBy;
            }
            set
            {
                this.RaisedBy = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("RaisedBy");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ChangeRequestStatus
        {
            get
            {
                return this.ChangeRequestStatus;
            }
            set
            {
                this.ChangeRequestStatus = (global::LightSwitchApplication.Implementation.ChangeRequestStatus)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ChangeRequestStatus");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ChangeOwner
        {
            get
            {
                return this.ChangeOwner;
            }
            set
            {
                this.ChangeOwner = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ChangeOwner");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ClosedBy
        {
            get
            {
                return this.ClosedBy;
            }
            set
            {
                this.ClosedBy = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ClosedBy");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ChangeQualifications
        {
            get
            {
                return this.ChangeQualifications;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.AssociatedRisks
        {
            get
            {
                return this.AssociatedRisks;
            }
        }
        
        partial void OnChangeRequest_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("RaisedBy");
            }
        }
        
        partial void OnChangeRequestStatus_ChangeRequestChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ChangeRequestStatus");
            }
        }
        
        partial void OnChangeRequest_Employee2Changed()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ChangeOwner");
            }
        }
        
        partial void OnChangeRequest_Employee1Changed()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ClosedBy");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeRequestStatus :
        global::LightSwitchApplication.ChangeRequestStatus.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeRequestStatus.DetailsClass.IImplementation.ChangeRequests
        {
            get
            {
                return this.ChangeRequests;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeRequestsRaisedBy
        {
            get
            {
                return this.ChangeRequestsRaisedBy;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeRequestsClosedBy
        {
            get
            {
                return this.ChangeRequestsClosedBy;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeRequestsChangeOwner
        {
            get
            {
                return this.ChangeRequestsChangeOwner;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.AssociatedRisk
        {
            get
            {
                return this.AssociatedRisk;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeQualificationActions
        {
            get
            {
                return this.ChangeQualificationActions;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeQualifications
        {
            get
            {
                return this.ChangeQualifications;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

