//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    /// <summary>
    /// Defines the names of the application permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static class Permissions
    {
        /// <summary>
        /// Provides the ability to manage security for the application.
        /// </summary>
        public const string SecurityAdministration = global::Microsoft.LightSwitch.Security.ApplicationPermissions.SecurityAdministration;
        /// <summary>
        /// Can Edit Associated Risks
        /// </summary>
        public const string CanEditAssociatedRisks = "LightSwitchApplication:CanEditAssociatedRisks";
        /// <summary>
        /// Can Edit Change Qualification Actions
        /// </summary>
        public const string CanEditChangeQualificationActions = "LightSwitchApplication:CanEditChangeQualificationActions";
        /// <summary>
        /// Can Edit Change Qualifications
        /// </summary>
        public const string CanEditChangeQualifications = "LightSwitchApplication:CanEditChangeQualifications";
        /// <summary>
        /// Can Edit Change Requests
        /// </summary>
        public const string CanEditChangeRequests = "LightSwitchApplication:CanEditChangeRequests";
        /// <summary>
        /// Can Edit Change Request Statuses
        /// </summary>
        public const string CanEditChangeRequestStatuses = "LightSwitchApplication:CanEditChangeRequestStatuses";
        /// <summary>
        /// Can Edit Employees
        /// </summary>
        public const string CanEditEmployees = "LightSwitchApplication:CanEditEmployees";

        /// <summary>
        /// Gets all permissions defined for the application.  This includes system and user-defined permissions.
        /// </summary>
        public static global::System.Collections.ObjectModel.ReadOnlyCollection<string> AllPermissions { get { return global::Microsoft.LightSwitch.Security.ApplicationPermissions.AllPermissions; } }
    }
}
