//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region AssociatedRisk
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssociatedRisk :
        global::LightSwitchApplication.AssociatedRisk.DetailsClass.IImplementation
    {
        partial void OnRiskAssessment_EmployeeChanged()
        {
            this.___OnPropertyChanged("RiskAssessment_Employee");
            this.___OnPropertyChanged("AssignedTo");
        }
        
        partial void OnChangeRequest_AssociatedRiskChanged()
        {
            this.___OnPropertyChanged("ChangeRequest_AssociatedRisk");
            this.___OnPropertyChanged("ChangeRequest");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRiskDescriptionChanged()
        {
            this.___OnPropertyChanged("RiskDescription");
        }
        
        partial void OnDateRaisedChanged()
        {
            this.___OnPropertyChanged("DateRaised");
        }
        
        partial void OnRiskLikelihoodChanged()
        {
            this.___OnPropertyChanged("RiskLikelihood");
        }
        
        partial void OnRiskImpactChanged()
        {
            this.___OnPropertyChanged("RiskImpact");
        }
        
        partial void OnTargetDateChanged()
        {
            this.___OnPropertyChanged("TargetDate");
        }
        
        partial void OnControlMeasuresChanged()
        {
            this.___OnPropertyChanged("ControlMeasures");
        }
        
        partial void OnDateCompletedChanged()
        {
            this.___OnPropertyChanged("DateCompleted");
        }
        
        partial void OnOverallRiskChanged()
        {
            this.___OnPropertyChanged("OverallRisk");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssociatedRisk.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __AssignedTo
        {
            get
            {
                if (this.___AssignedTo == null)
                {
                    this.___AssignedTo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "AssignedTo",
                        new string[] { "RiskAssessment_Employee" },
                        e => global::System.Object.Equals(e.Id, this.RiskAssessment_Employee),
                        () => this._AssignedTo,
                        e => this._AssignedTo = e);
                }
                return this.___AssignedTo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___AssignedTo;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssociatedRisk.DetailsClass.IImplementation.ChangeRequest
        {
            get
            {
                return this.ChangeRequest;
            }
            set
            {
                this.ChangeRequest = (global::LightSwitchApplication.Implementation.ChangeRequest)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequest> __ChangeRequest
        {
            get
            {
                if (this.___ChangeRequest == null)
                {
                    this.___ChangeRequest = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequest>(
                        this,
                        "ChangeRequest",
                        new string[] { "ChangeRequest_AssociatedRisk" },
                        e => global::System.Object.Equals(e.Id, this.ChangeRequest_AssociatedRisk),
                        () => this._ChangeRequest,
                        e => this._ChangeRequest = e);
                }
                return this.___ChangeRequest;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequest> ___ChangeRequest;
        
    }
    #endregion
    
    #region ChangeQualificationAction
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeQualificationAction :
        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.IImplementation
    {
        partial void OnChangeQualificationAction_ChangeQualificationChanged()
        {
            this.___OnPropertyChanged("ChangeQualificationAction_ChangeQualification");
            this.___OnPropertyChanged("ChangeQualification");
        }
        
        partial void OnChangeQualificationAction_EmployeeChanged()
        {
            this.___OnPropertyChanged("ChangeQualificationAction_Employee");
            this.___OnPropertyChanged("ActionAssignedTo");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnActionRequiredChanged()
        {
            this.___OnPropertyChanged("ActionRequired");
        }
        
        partial void OnDateActionAssignedChanged()
        {
            this.___OnPropertyChanged("DateActionAssigned");
        }
        
        partial void OnTargetActionCompletionDateChanged()
        {
            this.___OnPropertyChanged("TargetActionCompletionDate");
        }
        
        partial void OnActionTakenChanged()
        {
            this.___OnPropertyChanged("ActionTaken");
        }
        
        partial void OnDateActionCompletedChanged()
        {
            this.___OnPropertyChanged("DateActionCompleted");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.IImplementation.ChangeQualification
        {
            get
            {
                return this.ChangeQualification;
            }
            set
            {
                this.ChangeQualification = (global::LightSwitchApplication.Implementation.ChangeQualification)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeQualification> __ChangeQualification
        {
            get
            {
                if (this.___ChangeQualification == null)
                {
                    this.___ChangeQualification = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeQualification>(
                        this,
                        "ChangeQualification",
                        new string[] { "ChangeQualificationAction_ChangeQualification" },
                        e => global::System.Object.Equals(e.Id, this.ChangeQualificationAction_ChangeQualification),
                        () => this._ChangeQualification,
                        e => this._ChangeQualification = e);
                }
                return this.___ChangeQualification;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeQualification> ___ChangeQualification;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.IImplementation.ActionAssignedTo
        {
            get
            {
                return this.ActionAssignedTo;
            }
            set
            {
                this.ActionAssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __ActionAssignedTo
        {
            get
            {
                if (this.___ActionAssignedTo == null)
                {
                    this.___ActionAssignedTo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "ActionAssignedTo",
                        new string[] { "ChangeQualificationAction_Employee" },
                        e => global::System.Object.Equals(e.Id, this.ChangeQualificationAction_Employee),
                        () => this._ActionAssignedTo,
                        e => this._ActionAssignedTo = e);
                }
                return this.___ActionAssignedTo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___ActionAssignedTo;
        
    }
    #endregion
    
    #region ChangeQualification
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeQualification :
        global::LightSwitchApplication.ChangeQualification.DetailsClass.IImplementation
    {
        partial void OnChangeQualification_ChangeRequestChanged()
        {
            this.___OnPropertyChanged("ChangeQualification_ChangeRequest");
            this.___OnPropertyChanged("ChangeRequest");
        }
        
        partial void OnChangeQualification_Employee1Changed()
        {
            this.___OnPropertyChanged("ChangeQualification_Employee1");
            this.___OnPropertyChanged("AssignedTo");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnQualificationTypeChanged()
        {
            this.___OnPropertyChanged("QualificationType");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnStartDateChanged()
        {
            this.___OnPropertyChanged("StartDate");
        }
        
        partial void OnTargetCompletionDateChanged()
        {
            this.___OnPropertyChanged("TargetCompletionDate");
        }
        
        partial void OnDateClosedChanged()
        {
            this.___OnPropertyChanged("DateClosed");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeQualification.DetailsClass.IImplementation.ChangeRequest
        {
            get
            {
                return this.ChangeRequest;
            }
            set
            {
                this.ChangeRequest = (global::LightSwitchApplication.Implementation.ChangeRequest)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequest> __ChangeRequest
        {
            get
            {
                if (this.___ChangeRequest == null)
                {
                    this.___ChangeRequest = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequest>(
                        this,
                        "ChangeRequest",
                        new string[] { "ChangeQualification_ChangeRequest" },
                        e => global::System.Object.Equals(e.Id, this.ChangeQualification_ChangeRequest),
                        () => this._ChangeRequest,
                        e => this._ChangeRequest = e);
                }
                return this.___ChangeRequest;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequest> ___ChangeRequest;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeQualification.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __AssignedTo
        {
            get
            {
                if (this.___AssignedTo == null)
                {
                    this.___AssignedTo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "AssignedTo",
                        new string[] { "ChangeQualification_Employee1" },
                        e => global::System.Object.Equals(e.Id, this.ChangeQualification_Employee1),
                        () => this._AssignedTo,
                        e => this._AssignedTo = e);
                }
                return this.___AssignedTo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___AssignedTo;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeQualification.DetailsClass.IImplementation.ChangeQualificationActions
        {
            get
            {
                return this.ChangeQualificationActions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualificationAction> __ChangeQualificationActions
        {
            get
            {
                if (this.___ChangeQualificationActions == null)
                {
                    this.___ChangeQualificationActions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualificationAction>(
                        this,
                        "ChangeQualificationActions",
                        () => this._ChangeQualificationActions,
                        e => global::System.Object.Equals(e.ChangeQualificationAction_ChangeQualification, this.Id));
                }
                return this.___ChangeQualificationActions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualificationAction> ___ChangeQualificationActions;
        
    }
    #endregion
    
    #region ChangeRequest
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeRequest :
        global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation
    {
        partial void OnChangeRequest_EmployeeChanged()
        {
            this.___OnPropertyChanged("ChangeRequest_Employee");
            this.___OnPropertyChanged("RaisedBy");
        }
        
        partial void OnChangeRequestStatus_ChangeRequestChanged()
        {
            this.___OnPropertyChanged("ChangeRequestStatus_ChangeRequest");
            this.___OnPropertyChanged("ChangeRequestStatus");
        }
        
        partial void OnChangeRequest_Employee2Changed()
        {
            this.___OnPropertyChanged("ChangeRequest_Employee2");
            this.___OnPropertyChanged("ChangeOwner");
        }
        
        partial void OnChangeRequest_Employee1Changed()
        {
            this.___OnPropertyChanged("ChangeRequest_Employee1");
            this.___OnPropertyChanged("ClosedBy");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnReferenceChanged()
        {
            this.___OnPropertyChanged("Reference");
        }
        
        partial void OnChangeRequestTitleChanged()
        {
            this.___OnPropertyChanged("ChangeRequestTitle");
        }
        
        partial void OnChangeRequestDescriptionChanged()
        {
            this.___OnPropertyChanged("ChangeRequestDescription");
        }
        
        partial void OnDateRaisedChanged()
        {
            this.___OnPropertyChanged("DateRaised");
        }
        
        partial void OnTargetClosureDateChanged()
        {
            this.___OnPropertyChanged("TargetClosureDate");
        }
        
        partial void OnChangeRequestPlanChanged()
        {
            this.___OnPropertyChanged("ChangeRequestPlan");
        }
        
        partial void OnDateApprovedChanged()
        {
            this.___OnPropertyChanged("DateApproved");
        }
        
        partial void OnDateClosedChanged()
        {
            this.___OnPropertyChanged("DateClosed");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.RaisedBy
        {
            get
            {
                return this.RaisedBy;
            }
            set
            {
                this.RaisedBy = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __RaisedBy
        {
            get
            {
                if (this.___RaisedBy == null)
                {
                    this.___RaisedBy = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "RaisedBy",
                        new string[] { "ChangeRequest_Employee" },
                        e => global::System.Object.Equals(e.Id, this.ChangeRequest_Employee),
                        () => this._RaisedBy,
                        e => this._RaisedBy = e);
                }
                return this.___RaisedBy;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___RaisedBy;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ChangeRequestStatus
        {
            get
            {
                return this.ChangeRequestStatus;
            }
            set
            {
                this.ChangeRequestStatus = (global::LightSwitchApplication.Implementation.ChangeRequestStatus)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequestStatus> __ChangeRequestStatus
        {
            get
            {
                if (this.___ChangeRequestStatus == null)
                {
                    this.___ChangeRequestStatus = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequestStatus>(
                        this,
                        "ChangeRequestStatus",
                        new string[] { "ChangeRequestStatus_ChangeRequest" },
                        e => global::System.Object.Equals(e.Id, this.ChangeRequestStatus_ChangeRequest),
                        () => this._ChangeRequestStatus,
                        e => this._ChangeRequestStatus = e);
                }
                return this.___ChangeRequestStatus;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequestStatus> ___ChangeRequestStatus;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ChangeOwner
        {
            get
            {
                return this.ChangeOwner;
            }
            set
            {
                this.ChangeOwner = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __ChangeOwner
        {
            get
            {
                if (this.___ChangeOwner == null)
                {
                    this.___ChangeOwner = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "ChangeOwner",
                        new string[] { "ChangeRequest_Employee2" },
                        e => global::System.Object.Equals(e.Id, this.ChangeRequest_Employee2),
                        () => this._ChangeOwner,
                        e => this._ChangeOwner = e);
                }
                return this.___ChangeOwner;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___ChangeOwner;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ClosedBy
        {
            get
            {
                return this.ClosedBy;
            }
            set
            {
                this.ClosedBy = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __ClosedBy
        {
            get
            {
                if (this.___ClosedBy == null)
                {
                    this.___ClosedBy = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "ClosedBy",
                        new string[] { "ChangeRequest_Employee1" },
                        e => global::System.Object.Equals(e.Id, this.ChangeRequest_Employee1),
                        () => this._ClosedBy,
                        e => this._ClosedBy = e);
                }
                return this.___ClosedBy;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___ClosedBy;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ChangeQualifications
        {
            get
            {
                return this.ChangeQualifications;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualification> __ChangeQualifications
        {
            get
            {
                if (this.___ChangeQualifications == null)
                {
                    this.___ChangeQualifications = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualification>(
                        this,
                        "ChangeQualifications",
                        () => this._ChangeQualifications,
                        e => global::System.Object.Equals(e.ChangeQualification_ChangeRequest, this.Id));
                }
                return this.___ChangeQualifications;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualification> ___ChangeQualifications;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.AssociatedRisks
        {
            get
            {
                return this.AssociatedRisks;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssociatedRisk> __AssociatedRisks
        {
            get
            {
                if (this.___AssociatedRisks == null)
                {
                    this.___AssociatedRisks = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssociatedRisk>(
                        this,
                        "AssociatedRisks",
                        () => this._AssociatedRisks,
                        e => global::System.Object.Equals(e.ChangeRequest_AssociatedRisk, this.Id));
                }
                return this.___AssociatedRisks;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssociatedRisk> ___AssociatedRisks;
        
    }
    #endregion
    
    #region ChangeRequestStatus
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeRequestStatus :
        global::LightSwitchApplication.ChangeRequestStatus.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeRequestStatus.DetailsClass.IImplementation.ChangeRequests
        {
            get
            {
                return this.ChangeRequests;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> __ChangeRequests
        {
            get
            {
                if (this.___ChangeRequests == null)
                {
                    this.___ChangeRequests = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest>(
                        this,
                        "ChangeRequests",
                        () => this._ChangeRequests,
                        e => global::System.Object.Equals(e.ChangeRequestStatus_ChangeRequest, this.Id));
                }
                return this.___ChangeRequests;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> ___ChangeRequests;
        
    }
    #endregion
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCurrentChanged()
        {
            this.___OnPropertyChanged("Current");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeRequestsRaisedBy
        {
            get
            {
                return this.ChangeRequestsRaisedBy;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> __ChangeRequestsRaisedBy
        {
            get
            {
                if (this.___ChangeRequestsRaisedBy == null)
                {
                    this.___ChangeRequestsRaisedBy = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest>(
                        this,
                        "ChangeRequestsRaisedBy",
                        () => this._ChangeRequestsRaisedBy,
                        e => global::System.Object.Equals(e.ChangeRequest_Employee, this.Id));
                }
                return this.___ChangeRequestsRaisedBy;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> ___ChangeRequestsRaisedBy;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeRequestsClosedBy
        {
            get
            {
                return this.ChangeRequestsClosedBy;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> __ChangeRequestsClosedBy
        {
            get
            {
                if (this.___ChangeRequestsClosedBy == null)
                {
                    this.___ChangeRequestsClosedBy = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest>(
                        this,
                        "ChangeRequestsClosedBy",
                        () => this._ChangeRequestsClosedBy,
                        e => global::System.Object.Equals(e.ChangeRequest_Employee1, this.Id));
                }
                return this.___ChangeRequestsClosedBy;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> ___ChangeRequestsClosedBy;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeRequestsChangeOwner
        {
            get
            {
                return this.ChangeRequestsChangeOwner;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> __ChangeRequestsChangeOwner
        {
            get
            {
                if (this.___ChangeRequestsChangeOwner == null)
                {
                    this.___ChangeRequestsChangeOwner = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest>(
                        this,
                        "ChangeRequestsChangeOwner",
                        () => this._ChangeRequestsChangeOwner,
                        e => global::System.Object.Equals(e.ChangeRequest_Employee2, this.Id));
                }
                return this.___ChangeRequestsChangeOwner;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> ___ChangeRequestsChangeOwner;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.AssociatedRisk
        {
            get
            {
                return this.AssociatedRisk;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssociatedRisk> __AssociatedRisk
        {
            get
            {
                if (this.___AssociatedRisk == null)
                {
                    this.___AssociatedRisk = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssociatedRisk>(
                        this,
                        "AssociatedRisk",
                        () => this._AssociatedRisk,
                        e => global::System.Object.Equals(e.RiskAssessment_Employee, this.Id));
                }
                return this.___AssociatedRisk;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssociatedRisk> ___AssociatedRisk;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeQualificationActions
        {
            get
            {
                return this.ChangeQualificationActions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualificationAction> __ChangeQualificationActions
        {
            get
            {
                if (this.___ChangeQualificationActions == null)
                {
                    this.___ChangeQualificationActions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualificationAction>(
                        this,
                        "ChangeQualificationActions",
                        () => this._ChangeQualificationActions,
                        e => global::System.Object.Equals(e.ChangeQualificationAction_Employee, this.Id));
                }
                return this.___ChangeQualificationActions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualificationAction> ___ChangeQualificationActions;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeQualifications
        {
            get
            {
                return this.ChangeQualifications;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualification> __ChangeQualifications
        {
            get
            {
                if (this.___ChangeQualifications == null)
                {
                    this.___ChangeQualifications = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualification>(
                        this,
                        "ChangeQualifications",
                        () => this._ChangeQualifications,
                        e => global::System.Object.Equals(e.ChangeQualification_Employee1, this.Id));
                }
                return this.___ChangeQualifications;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeQualification> ___ChangeQualifications;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.AssociatedRisk))
            {
                return new global::LightSwitchApplication.Implementation.AssociatedRisk();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeQualificationAction))
            {
                return new global::LightSwitchApplication.Implementation.ChangeQualificationAction();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeQualification))
            {
                return new global::LightSwitchApplication.Implementation.ChangeQualification();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeRequest))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequest();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeRequestStatus))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequestStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.AssociatedRisk) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssociatedRisk);
            }
            if (typeof(global::LightSwitchApplication.ChangeQualificationAction) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeQualificationAction);
            }
            if (typeof(global::LightSwitchApplication.ChangeQualification) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeQualification);
            }
            if (typeof(global::LightSwitchApplication.ChangeRequest) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeRequest);
            }
            if (typeof(global::LightSwitchApplication.ChangeRequestStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeRequestStatus);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            return null;
        }
    }
}
