

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class ChangeQualificationAction : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ChangeQualificationAction entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ChangeQualificationAction()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ChangeQualificationAction(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ChangeQualificationAction> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeQualificationAction_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeQualificationAction_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ActionRequired
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionRequired);
            }
            set
            {
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionRequired, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionRequired_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionRequired_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionRequired_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateActionAssigned
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.DateActionAssigned);
            }
            set
            {
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.DateActionAssigned, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateActionAssigned_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateActionAssigned_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateActionAssigned_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> TargetActionCompletionDate
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.TargetActionCompletionDate);
            }
            set
            {
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.TargetActionCompletionDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetActionCompletionDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetActionCompletionDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetActionCompletionDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ActionTaken
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionTaken);
            }
            set
            {
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionTaken, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionTaken_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionTaken_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionTaken_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateActionCompleted
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.DateActionCompleted);
            }
            set
            {
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.DateActionCompleted, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateActionCompleted_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateActionCompleted_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateActionCompleted_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ChangeQualification ChangeQualification
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ChangeQualification);
            }
            set
            {
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ChangeQualification, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeQualification_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeQualification_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeQualification_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Employee ActionAssignedTo
        {
            get
            {
                return global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionAssignedTo);
            }
            set
            {
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionAssignedTo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionAssignedTo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionAssignedTo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionAssignedTo_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ChangeQualificationAction,
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass,
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.IImplementation,
                global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass>.Entry
                __ChangeQualificationActionEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass>.Entry(
                    global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.__ChangeQualificationAction_CreateNew,
                    global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.__ChangeQualificationAction_Created,
                    global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.__ChangeQualificationAction_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ChangeQualificationAction __ChangeQualificationAction_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ChangeQualificationAction> es)
            {
                return new global::LightSwitchApplication.ChangeQualificationAction(es);
            }
            private static void __ChangeQualificationAction_Created(global::LightSwitchApplication.ChangeQualificationAction e)
            {
                e.ChangeQualificationAction_Created();
            }
            private static bool __ChangeQualificationAction_AllowSaveWithErrors(global::LightSwitchApplication.ChangeQualificationAction e)
            {
                bool result = false;
                e.ChangeQualificationAction_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string> ActionRequired
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionRequired) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>> DateActionAssigned
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.DateActionAssigned) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>> TargetActionCompletionDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.TargetActionCompletionDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string> ActionTaken
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionTaken) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>> DateActionCompleted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.DateActionCompleted) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.ChangeQualification> ChangeQualification
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ChangeQualification) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.ChangeQualification>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.Employee> ActionAssignedTo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionAssignedTo) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.Employee>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string ActionRequired { get; set; }
                new global::System.Nullable<global::System.DateTime> DateActionAssigned { get; set; }
                new global::System.Nullable<global::System.DateTime> TargetActionCompletionDate { get; set; }
                new string ActionTaken { get; set; }
                new global::System.Nullable<global::System.DateTime> DateActionCompleted { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ChangeQualification { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ActionAssignedTo { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, int>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Entry
                    ActionRequired = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Entry(
                        "ActionRequired",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionRequired_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionRequired_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionRequired_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionRequired_GetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionRequired_SetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionRequired_OnValueChanged);
                private static void _ActionRequired_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._ActionRequired, sf);
                }
                private static bool _ActionRequired_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.ActionRequired_IsReadOnly(ref result);
                    return result;
                }
                private static void _ActionRequired_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ActionRequired_Validate(r);
                }
                private static string _ActionRequired_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.ActionRequired;
                }
                private static void _ActionRequired_SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ActionRequired = v;
                }
                private static void _ActionRequired_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.ActionRequired_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateActionAssigned = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateActionAssigned",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionAssigned_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionAssigned_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionAssigned_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionAssigned_GetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionAssigned_SetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionAssigned_OnValueChanged);
                private static void _DateActionAssigned_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._DateActionAssigned, sf);
                }
                private static bool _DateActionAssigned_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.DateActionAssigned_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateActionAssigned_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateActionAssigned_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateActionAssigned_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.DateActionAssigned;
                }
                private static void _DateActionAssigned_SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateActionAssigned = global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.TruncateDate(v);
                }
                private static void _DateActionAssigned_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.DateActionAssigned_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    TargetActionCompletionDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "TargetActionCompletionDate",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._TargetActionCompletionDate_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._TargetActionCompletionDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._TargetActionCompletionDate_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._TargetActionCompletionDate_GetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._TargetActionCompletionDate_SetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._TargetActionCompletionDate_OnValueChanged);
                private static void _TargetActionCompletionDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._TargetActionCompletionDate, sf);
                }
                private static bool _TargetActionCompletionDate_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.TargetActionCompletionDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _TargetActionCompletionDate_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TargetActionCompletionDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _TargetActionCompletionDate_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.TargetActionCompletionDate;
                }
                private static void _TargetActionCompletionDate_SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.TargetActionCompletionDate = global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.TruncateDate(v);
                }
                private static void _TargetActionCompletionDate_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.TargetActionCompletionDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Entry
                    ActionTaken = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Entry(
                        "ActionTaken",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionTaken_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionTaken_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionTaken_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionTaken_GetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionTaken_SetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionTaken_OnValueChanged);
                private static void _ActionTaken_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._ActionTaken, sf);
                }
                private static bool _ActionTaken_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.ActionTaken_IsReadOnly(ref result);
                    return result;
                }
                private static void _ActionTaken_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ActionTaken_Validate(r);
                }
                private static string _ActionTaken_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.ActionTaken;
                }
                private static void _ActionTaken_SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ActionTaken = v;
                }
                private static void _ActionTaken_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.ActionTaken_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateActionCompleted = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateActionCompleted",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionCompleted_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionCompleted_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionCompleted_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionCompleted_GetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionCompleted_SetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._DateActionCompleted_OnValueChanged);
                private static void _DateActionCompleted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._DateActionCompleted, sf);
                }
                private static bool _DateActionCompleted_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.DateActionCompleted_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateActionCompleted_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateActionCompleted_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateActionCompleted_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.DateActionCompleted;
                }
                private static void _DateActionCompleted_SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateActionCompleted = global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.TruncateDate(v);
                }
                private static void _DateActionCompleted_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.DateActionCompleted_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.ChangeQualification>.Entry
                    ChangeQualification = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.ChangeQualification>.Entry(
                        "ChangeQualification",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ChangeQualification_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ChangeQualification_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ChangeQualification_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ChangeQualification_GetCoreImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ChangeQualification_GetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ChangeQualification_SetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ChangeQualification_Refresh,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ChangeQualification_OnValueChanged);
                private static void _ChangeQualification_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.ChangeQualification>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._ChangeQualification, sf);
                }
                private static bool _ChangeQualification_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.ChangeQualification_IsReadOnly(ref result);
                    return result;
                }
                private static void _ChangeQualification_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ChangeQualification_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ChangeQualification_GetCoreImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.ChangeQualification;
                }
                private static global::LightSwitchApplication.ChangeQualification _ChangeQualification_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ChangeQualification, global::LightSwitchApplication.ChangeQualification.DetailsClass>(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ChangeQualification, ref d._ChangeQualification);
                }
                private static void _ChangeQualification_SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, global::LightSwitchApplication.ChangeQualification v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ChangeQualification, ref d._ChangeQualification, (i, ev) => i.ChangeQualification = ev, v);
                }
                private static void _ChangeQualification_Refresh(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ChangeQualification, ref d._ChangeQualification);
                }
                private static void _ChangeQualification_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.ChangeQualification_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.Employee>.Entry
                    ActionAssignedTo = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.Employee>.Entry(
                        "ActionAssignedTo",
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionAssignedTo_Stub,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionAssignedTo_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionAssignedTo_Validate,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionAssignedTo_GetCoreImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionAssignedTo_GetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionAssignedTo_SetImplementationValue,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionAssignedTo_Refresh,
                        global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties._ActionAssignedTo_OnValueChanged);
                private static void _ActionAssignedTo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.Employee>.Data> c, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, object sf)
                {
                    c(d, ref d._ActionAssignedTo, sf);
                }
                private static bool _ActionAssignedTo_ComputeIsReadOnly(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    bool result = false;
                    e.ActionAssignedTo_IsReadOnly(ref result);
                    return result;
                }
                private static void _ActionAssignedTo_Validate(global::LightSwitchApplication.ChangeQualificationAction e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ActionAssignedTo_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ActionAssignedTo_GetCoreImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.ImplementationEntity.ActionAssignedTo;
                }
                private static global::LightSwitchApplication.Employee _ActionAssignedTo_GetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Employee, global::LightSwitchApplication.Employee.DetailsClass>(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionAssignedTo, ref d._ActionAssignedTo);
                }
                private static void _ActionAssignedTo_SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d, global::LightSwitchApplication.Employee v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionAssignedTo, ref d._ActionAssignedTo, (i, ev) => i.ActionAssignedTo = ev, v);
                }
                private static void _ActionAssignedTo_Refresh(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ChangeQualificationAction.DetailsClass.PropertySetProperties.ActionAssignedTo, ref d._ActionAssignedTo);
                }
                private static void _ActionAssignedTo_OnValueChanged(global::LightSwitchApplication.ChangeQualificationAction e)
                {
                    e.ActionAssignedTo_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Data _ActionRequired;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateActionAssigned;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _TargetActionCompletionDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Data _ActionTaken;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateActionCompleted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.ChangeQualification>.Data _ChangeQualification;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeQualificationAction, global::LightSwitchApplication.ChangeQualificationAction.DetailsClass, global::LightSwitchApplication.Employee>.Data _ActionAssignedTo;
            
        }
    
        #endregion
    }
    
    #endregion
}
